sudo: required
language: c
os:
  - linux
  - osx
services: docker
before_install:
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;linux&quot; ]]; then sudo apt-get -qq update; fi
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;linux&quot; ]]; then sudo apt-get install -y aspcud; fi
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;osx&quot; ]]; then brew update; fi
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;osx&quot; ]]; then brew unlink python; fi
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;osx&quot; ]]; then brew install opam; fi
install:
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;osx&quot; ]]; then opam init --reinit --no-setup --disable-sandboxing; fi
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;osx&quot; ]]; then travis_wait 60 opam install --yes .; fi
script:
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;osx&quot; ]]; then ./.travis/local_install_tests.sh; fi
  - if [[ &quot;$TRAVIS_OS_NAME&quot; == &quot;linux&quot; ]]; then ./.travis/docker_tests.sh; fi
  - git diff --exit-code
